services:
  backend:
    build: ./backend
    command: sh -c "python3 -m src"
    ports:
      - "8000:8001"
    stop_signal: SIGINT
    restart: unless-stopped
    volumes:
      - ./backend:/usr/src/hackaton/backend
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    networks:
      - api-network


networks:
  api-network:
    driver: bridge
