"""empty message

Revision ID: f9685d7f83cf
Revises: 160baaef07bb
Create Date: 2025-05-25 13:31:34.275707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9685d7f83cf'
down_revision: Union[str, None] = '160baaef07bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_monthly_consumption_client_id_client'), 'monthly_consumption', type_='foreignkey')
    op.create_foreign_key(op.f('fk_monthly_consumption_client_id_client'), 'monthly_consumption', 'client', ['client_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('suspicious_client', sa.Column('verdict', sa.Boolean(), nullable=True, comment='Verdict after checking the suspicious client'))
    op.drop_constraint(op.f('fk_suspicious_client_client_id_client'), 'suspicious_client', type_='foreignkey')
    op.create_foreign_key(op.f('fk_suspicious_client_client_id_client'), 'suspicious_client', 'client', ['client_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_suspicious_client_client_id_client'), 'suspicious_client', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_suspicious_client_client_id_client'), 'suspicious_client', 'client', ['client_id'], ['id'])
    op.drop_column('suspicious_client', 'verdict')
    op.drop_constraint(op.f('fk_monthly_consumption_client_id_client'), 'monthly_consumption', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_monthly_consumption_client_id_client'), 'monthly_consumption', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###
